/* Automatically generated by './build/bin/build-examples-home.js' */
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png" />
    <nav>
      <ul>
        <li><router-link to="/button">Button</router-link></li>
      </ul>
    </nav>
  </div>
</template>

<script>
export default {
  name: "Home"
};
</script>
