/* Automatically generated by './build/bin/build-examples-home.js' */
<template>
  <div class="home">
    <nav>
      <ul>
        <li v-for="(e, i) in links" :key="'e' + i">
          <router-link :to="`/${e}`">{{ e }}</router-link>
        </li>
      </ul>
    </nav>
  </div>
</template>

<script>
  export default {
    name: 'Home',
    data() {
      return {
        links: ['button', 'dialog', 'masker', 'indicator', 'title'],
      }
    },
  }
</script>
<style lang="scss" scoped></style>
