/* Automatically generated by './build/bin/build-examples-home.js' */
<template>
  <div class="home">
    <nav>
      <ul>
        <li><router-link to="/button">Button</router-link></li>
        <li><router-link to="/dialog">dialog</router-link></li>
        <li><router-link to="/masker">masker</router-link></li>
      </ul>
    </nav>
  </div>
</template>

<script>
  export default {
    name: 'Home',
  }
</script>
<style lang="scss" scoped></style>
