/* Automatically generated by './build/bin/build-routers.js' */

import Vue from "vue";
import VueRouter from "vue-router";
import Home from "../views/Home";

Vue.use(VueRouter);

const routes = [
  {
    path: "/",
    name: "Home",
    component: Home
  },
  {
    path: "/button",
    component: resolve => require(["../views/button.vue"], resolve)
  },
];

const router = new VueRouter({
  mode: "history",
  routes
});
export default router;
