/* Automatically generated by './build/bin/build-routers.js' */

import Vue from 'vue'
import VueRouter from 'vue-router'
import Home from '../views/Home'
Vue.use(VueRouter)

const routes = [
  {
    path: '/',
    name: 'Home',
    component: Home,
  },
  {
    path: '/button',
    name: 'button',
    // route level code-splitting
    // this generates a separate chunk (about.[hash].js) for this route
    // which is lazy-loaded when the route is visited.
    component: () => import(/* webpackChunkName: "about" */ '../views/button.vue'),
  },
  {
    path: '/dialog',
    name: 'dialog',
    component: () => import(/* webpackChunkName: "about" */ '../views/dialog.vue'),
  },
  {
    path: '/masker',
    name: 'masker',
    component: () => import(/* webpackChunkName: "about" */ '../views/masker.vue'),
  },
  {
    path: '/indicator',
    name: 'indicator',
    component: () => import(/* webpackChunkName: "about" */ '../views/indicator.vue'),
  },
]

export default routes
