/* Automatically generated by './build/bin/build-entry.js' */

import simButton from "./Button";

const components = [
  simButton,
];

const install = function(Vue) {
  components.forEach(component => {
    Vue.component(component.name, component);
    if (component.Item) {
      Vue.component(component.Item.name, component.Item);
    }
  });
};

/* istanbul ignore if */
if (typeof window !== "undefined" && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  simButton,
};
